### ISSUE TITLE
Error spam when compatible mod is missing

### ISSUE THREAD

**Issue by Auuki** [ManaStar/compat-o-plenty#38] opened 2023-05-03 20:35 UTC
When a compatible mod is missing (for instance Woodworks), logs get spammed with errors. Instead it should skip that mod if it's not present.

**Comment by ManaStar** [comment] 2023-05-03 20:56
So either I'm going to need a latest.log, or I'm going to close this as a duplicate of #35 as this already sounds extremely similar

**Comment by ManaStar** [comment] 2023-05-15 05:30
Since I've had no response for the last 2 weeks, I'll be closing this as the root cause should be fixed. If that remains the case after the next release please feel free to reopen this issue!

**Closed as completed by ManaStar** 2023-05-15 05:30 UTC
